language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew war
  - ./gradlew test

notifications:
  email:
    recipients:
      - sharma.j@husky.neu.edu

after_success:
  - mkdir codedeploy
  - zip -r SimpleJavaProject-${TRAVIS_JOB_NUMBER}.zip build/libs/Root.war appspec.yml
  - ls -al
  - mv SimpleJavaProject-${TRAVIS_JOB_NUMBER}.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd

before_deploy:
  - cd ..

deploy:
  - provider: s3
    access_key_id: X
    secret_access_key:
      secure:  X
    local_dir: codedeploy
    bucket: csye6225-fall2017-muralia.me.csye6225.com
    region: us-east-1
    skip_cleanup: true


  - provider: codedeploy
    access_key_id: X
    bucket: csye6225-fall2017-muralia.me.csye6225.com
    key: csye6225-spring-boot-starter-webapp-master.zip
    bundle_type: zip
    application: myProject
    deployment_group: myProject
    region: us-east-1
    secret_access_key:
      secure:  X
    wait-until-deployed: true
