language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew war
  - ./gradlew test

notifications:
  email:
    recipients:
      - murali.a@husky.neu.edu
      - patil.sur@husky.neu.edu
      - sharma.j@husky.neu.edu
