/**
 * Amitha_Murali, 001643826, murali.a@husky.neu.edu
 * Jyoti Sharma, 001643410, sharma.j@husky.neu.edu
 * Surabhi Patil, 001251860, patil.sur@husky.neu.edu
 **/

language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew war

notifications:
  email:
    recipients:
      - murali.a@husky.neu.edu
